apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-release-tempo-query-frontend
  namespace: tempo
  uid: 4ea687f6-25f9-49f2-a126-14fa3106093d
  resourceVersion: '4757'
  generation: 1
  creationTimestamp: '2025-01-25T18:54:09Z'
  labels:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tempo
    app.kubernetes.io/version: 2.7.0
    helm.sh/chart: tempo-distributed-1.31.0
  annotations:
    deployment.kubernetes.io/revision: '1'
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: tempo
  selfLink: /apis/apps/v1/namespaces/tempo/deployments/my-release-tempo-query-frontend
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2025-01-25T18:54:09Z'
      lastTransitionTime: '2025-01-25T18:54:09Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2025-01-25T18:55:00Z'
      lastTransitionTime: '2025-01-25T18:54:09Z'
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet "my-release-tempo-query-frontend-78d6c6946d" has successfully
        progressed.
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: query-frontend
      app.kubernetes.io/instance: my-release
      app.kubernetes.io/name: tempo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: query-frontend
        app.kubernetes.io/instance: my-release
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: tempo
        app.kubernetes.io/version: 2.7.0
        helm.sh/chart: tempo-distributed-1.31.0
      annotations:
        checksum/config: b7efa005e45e6ce9cf1f7991f6eeb7bd1028c3d680d3c77ef323e4141c809657
    spec:
      volumes:
        - name: config
          configMap:
            name: my-release-tempo-config
            items:
              - key: tempo.yaml
                path: tempo.yaml
            defaultMode: 420
        - name: runtime-config
          configMap:
            name: my-release-tempo-runtime
            items:
              - key: overrides.yaml
                path: overrides.yaml
            defaultMode: 420
        - name: tempo-queryfrontend-store
          emptyDir: {}
      containers:
        - name: query-frontend
          image: docker.io/grafana/tempo:2.7.0
          args:
            - '-target=query-frontend'
            - '-config.file=/conf/tempo.yaml'
            - '-mem-ballast-size-mbs=1024'
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /conf
            - name: runtime-config
              mountPath: /runtime-config
            - name: tempo-queryfrontend-store
              mountPath: /var/tempo
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: my-release-tempo
      serviceAccount: my-release-tempo
      securityContext:
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: query-frontend
                  app.kubernetes.io/instance: my-release
                  app.kubernetes.io/name: tempo
              topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: query-frontend
                    app.kubernetes.io/instance: my-release
                    app.kubernetes.io/name: tempo
                topologyKey: topology.kubernetes.io/zone
      schedulerName: default-scheduler
      enableServiceLinks: false
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: query-frontend
              app.kubernetes.io/instance: my-release
              app.kubernetes.io/name: tempo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  minReadySeconds: 10
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
