apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-release-tempo-ingester
  namespace: tempo
  uid: 00db2fa9-18df-4ac2-802d-7c910156d475
  resourceVersion: '4906'
  generation: 1
  creationTimestamp: '2025-01-25T18:54:09Z'
  labels:
    app.kubernetes.io/component: ingester
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tempo
    app.kubernetes.io/part-of: memberlist
    app.kubernetes.io/version: 2.7.0
    helm.sh/chart: tempo-distributed-1.31.0
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: tempo
  selfLink: /apis/apps/v1/namespaces/tempo/statefulsets/my-release-tempo-ingester
status:
  observedGeneration: 1
  replicas: 3
  readyReplicas: 3
  currentReplicas: 3
  updatedReplicas: 3
  currentRevision: my-release-tempo-ingester-6bb478c57f
  updateRevision: my-release-tempo-ingester-6bb478c57f
  collisionCount: 0
  availableReplicas: 3
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: ingester
      app.kubernetes.io/instance: my-release
      app.kubernetes.io/name: tempo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: ingester
        app.kubernetes.io/instance: my-release
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: tempo
        app.kubernetes.io/part-of: memberlist
        app.kubernetes.io/version: 2.7.0
        helm.sh/chart: tempo-distributed-1.31.0
      annotations:
        checksum/config: b7efa005e45e6ce9cf1f7991f6eeb7bd1028c3d680d3c77ef323e4141c809657
    spec:
      volumes:
        - name: config
          configMap:
            name: my-release-tempo-config
            items:
              - key: tempo.yaml
                path: tempo.yaml
            defaultMode: 420
        - name: runtime-config
          configMap:
            name: my-release-tempo-runtime
            items:
              - key: overrides.yaml
                path: overrides.yaml
            defaultMode: 420
        - name: data
          emptyDir: {}
      containers:
        - name: ingester
          image: docker.io/grafana/tempo:2.7.0
          args:
            - '-target=ingester'
            - '-config.file=/conf/tempo.yaml'
            - '-mem-ballast-size-mbs=1024'
          ports:
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: http-memberlist
              containerPort: 7946
              protocol: TCP
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /conf
            - name: runtime-config
              mountPath: /runtime-config
            - name: data
              mountPath: /var/tempo
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 300
      dnsPolicy: ClusterFirst
      serviceAccountName: my-release-tempo
      serviceAccount: my-release-tempo
      securityContext:
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: ingester
                    app.kubernetes.io/instance: my-release
                    app.kubernetes.io/name: tempo
                topologyKey: kubernetes.io/hostname
            - weight: 75
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: ingester
                    app.kubernetes.io/instance: my-release
                    app.kubernetes.io/name: tempo
                topologyKey: topology.kubernetes.io/zone
      schedulerName: default-scheduler
      enableServiceLinks: false
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: ingester
              app.kubernetes.io/instance: my-release
              app.kubernetes.io/name: tempo
  serviceName: ingester
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
