apiVersion: v1
kind: Service
metadata:
  name: my-release-tempo-query-frontend-discovery
  namespace: tempo
  uid: fa6896ce-6322-48ae-abf1-7299766eeae4
  resourceVersion: '4447'
  creationTimestamp: '2025-01-25T18:54:09Z'
  labels:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tempo
    app.kubernetes.io/version: 2.7.0
    helm.sh/chart: tempo-distributed-1.31.0
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: tempo
  selfLink: /api/v1/namespaces/tempo/services/my-release-tempo-query-frontend-discovery
status:
  loadBalancer: {}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3100
      targetPort: 3100
    - name: grpc
      protocol: TCP
      port: 9095
      targetPort: 9095
    - name: grpclb
      protocol: TCP
      port: 9096
      targetPort: grpc
  selector:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: tempo
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  publishNotReadyAddresses: true
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
