apiVersion: v1
kind: Service
metadata:
  name: my-release-tempo-query-frontend
  namespace: tempo
  uid: 23441b9a-0b21-4f49-9595-0182d322f66f
  resourceVersion: '4437'
  creationTimestamp: '2025-01-25T18:54:09Z'
  labels:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tempo
    app.kubernetes.io/version: 2.7.0
    helm.sh/chart: tempo-distributed-1.31.0
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: tempo
  selfLink: /api/v1/namespaces/tempo/services/my-release-tempo-query-frontend
status:
  loadBalancer: {}
spec:
  ports:
    - name: http-metrics
      protocol: TCP
      port: 3100
      targetPort: 3100
    - name: grpc
      protocol: TCP
      port: 9095
      targetPort: 9095
  selector:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: tempo
  clusterIP: 10.96.221.169
  clusterIPs:
    - 10.96.221.169
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
