apiVersion: v1
kind: Service
metadata:
  name: my-release-tempo-querier
  namespace: tempo
  uid: 8ceb4a8d-2af2-4845-b4f8-afd12ad4ebb3
  resourceVersion: '4468'
  creationTimestamp: '2025-01-25T18:54:09Z'
  labels:
    app.kubernetes.io/component: querier
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tempo
    app.kubernetes.io/version: 2.7.0
    helm.sh/chart: tempo-distributed-1.31.0
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: tempo
  selfLink: /api/v1/namespaces/tempo/services/my-release-tempo-querier
status:
  loadBalancer: {}
spec:
  ports:
    - name: http-metrics
      protocol: TCP
      port: 3100
      targetPort: 3100
    - name: grpc
      protocol: TCP
      port: 9095
      targetPort: 9095
  selector:
    app.kubernetes.io/component: querier
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: tempo
  clusterIP: 10.96.243.117
  clusterIPs:
    - 10.96.243.117
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
